"""Generate Go and Python representations from the canonical contract source."""

from __future__ import annotations

import json
import os
from pathlib import Path
import tempfile
from typing import Any


CONTRACT_NAMES = (
    "procedure_step",
    "visual_artifact",
    "price_snapshot",
    "chat_quote",
    "chat_answer",
    "chat_query",
    "chat_selection",
    "worker_progress_event",
    "dataset_read",
    "knowledge_search_response",
    "knowledge_result",
    "knowledge_article",
    "knowledge_procedure",
    "knowledge_evidence",
    "dataset_section",
    "dataset_request",
    "entitlement",
    "evidence",
    "feedback",
    "error",
    "event_envelope",
)


def load_contract(path: Path) -> dict[str, Any]:
    contract = json.loads(path.read_text())
    required_top_level = {
        "schema_version",
        "data_state",
        "answer_status",
        "dataset_availability",
        "section_status",
        "event_subjects",
        "knowledge_result_kind",
        *CONTRACT_NAMES,
    }
    missing = required_top_level - contract.keys()
    if missing:
        raise ValueError(f"contract is missing top-level keys: {sorted(missing)}")
    if not isinstance(contract["schema_version"], int) or contract["schema_version"] < 1:
        raise ValueError("schema_version must be a positive integer")
    for enum_name in ("data_state", "answer_status", "knowledge_result_kind"):
        if not isinstance(contract[enum_name], list) or not contract[enum_name]:
            raise ValueError(f"{enum_name} must be a non-empty list")
    for name in CONTRACT_NAMES:
        definition = contract[name]
        required = definition.get("required")
        properties = definition.get("properties")
        if not isinstance(required, list) or not isinstance(properties, dict):
            raise ValueError(f"{name} must declare required and properties")
        if not set(required).issubset(properties):
            raise ValueError(f"{name} requires an undeclared property")
    if contract["price_snapshot"]["properties"].get("markup_applied") != {
        "type": "boolean",
        "const": False,
    }:
        raise ValueError("price_snapshot.markup_applied must be a boolean const false")
    return contract


def is_backward_compatible_addition(old: dict[str, Any], new: dict[str, Any]) -> bool:
    """Allow new optional properties while preserving old required behavior."""

    old_required = set(old.get("required", []))
    new_required = set(new.get("required", []))
    old_properties = set(old.get("properties", {}))
    new_properties = set(new.get("properties", {}))
    return old_required == new_required and old_properties.issubset(new_properties)


def write_generated(path: Path, content: str) -> None:
    """Replace generated output atomically so parallel checks never read a partial file."""

    temporary_name: str | None = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w", dir=path.parent, prefix=f".{path.name}.", delete=False
        ) as temporary:
            temporary.write(content)
            temporary_name = temporary.name
        os.replace(temporary_name, path)
        temporary_name = None
    finally:
        if temporary_name:
            Path(temporary_name).unlink(missing_ok=True)


def _json_strings(values: list[str]) -> str:
    return ", ".join(json.dumps(value) for value in values)


def _go_enum(name: str, values: list[str]) -> str:
    return f"var {name} = []string{{{_json_strings(values)}}}\n"


def _enum_values(contract: dict[str, Any], contract_name: str, property_name: str) -> list[str]:
    return contract[contract_name]["properties"][property_name]["enum"]


def render_go(contract: dict[str, Any]) -> str:
    return """// Code generated by scripts/contracts/generate.py; DO NOT EDIT.
package contracts

const SchemaVersion = %(schema_version)d

%(data_state)s%(answer_status)s%(dataset_availability)s%(section_status)s%(event_subjects)s%(knowledge_result_kind)s%(entitlement_status)s%(feedback_category)s%(error_codes)s
var DatasetReadRequiredFields = []string{%(dataset_read_required)s}
var KnowledgeSearchResponseRequiredFields = []string{%(knowledge_search_response_required)s}
var KnowledgeResultRequiredFields = []string{%(knowledge_result_required)s}
var KnowledgeArticleRequiredFields = []string{%(knowledge_article_required)s}
var KnowledgeProcedureRequiredFields = []string{%(knowledge_procedure_required)s}
var KnowledgeEvidenceRequiredFields = []string{%(knowledge_evidence_required)s}
var DatasetRequestRequiredFields = []string{%(dataset_request_required)s}
var EntitlementRequiredFields = []string{%(entitlement_required)s}
var EvidenceRequiredFields = []string{%(evidence_required)s}
var FeedbackRequiredFields = []string{%(feedback_required)s}
var ErrorRequiredFields = []string{%(error_required)s}
var EventEnvelopeRequiredFields = []string{%(event_envelope_required)s}
var ProcedureStepRequiredFields = []string{%(procedure_step_required)s}
var VisualArtifactRequiredFields = []string{%(visual_artifact_required)s}
var PriceSnapshotRequiredFields = []string{%(price_snapshot_required)s}
var ChatQuoteRequiredFields = []string{%(chat_quote_required)s}
var ChatAnswerRequiredFields = []string{%(chat_answer_required)s}
var ChatQueryRequiredFields = []string{%(chat_query_required)s}
var ChatSelectionRequiredFields = []string{%(chat_selection_required)s}
var WorkerProgressEventRequiredFields = []string{%(worker_progress_event_required)s}

type DatasetSection struct {
	Name                  string  `json:"name"`
	Status                string  `json:"status"`
	LastPublishedRevision *string `json:"last_published_revision"`
	UpdatedAt             string  `json:"updated_at"`
}

type DatasetReadEnvelope struct {
	DatasetID       string           `json:"dataset_id"`
	RevisionID      string           `json:"revision_id"`
	Availability    string           `json:"availability"`
	SourceWatermark string           `json:"source_watermark"`
	Sections        []DatasetSection `json:"sections"`
}

type KnowledgeSearchResponse struct {
	DatasetID       string                 `json:"dataset_id"`
	RevisionID      string                 `json:"revision_id"`
	Availability    string                 `json:"availability"`
	SourceWatermark string                 `json:"source_watermark"`
	Sections        []DatasetSection       `json:"sections"`
	VehicleIdentity map[string]any         `json:"vehicle_identity,omitempty"`
	FallbackStatus   string                 `json:"fallback_status,omitempty"`
	FallbackRequestID string                `json:"fallback_request_id,omitempty"`
	Results         []KnowledgeResult      `json:"results"`
}

type KnowledgeResult struct {
	Kind      string             `json:"kind"`
	ID        string             `json:"id"`
	Score     float64            `json:"score"`
	Article   *KnowledgeArticle  `json:"article,omitempty"`
	Procedure *KnowledgeProcedure `json:"procedure,omitempty"`
	Evidence  []KnowledgeEvidence `json:"evidence"`
}

type KnowledgeArticle struct {
	ArticleID      string `json:"article_id"`
	ArticleKey     string `json:"article_key,omitempty"`
	Bucket         string `json:"bucket,omitempty"`
	Title          string `json:"title,omitempty"`
	BulletinNumber string `json:"bulletin_number,omitempty"`
	ReleaseDate    string `json:"release_date,omitempty"`
	Body           string `json:"body,omitempty"`
	Steps          []any  `json:"steps,omitempty"`
}

type KnowledgeProcedure struct {
	ProcedureID  string   `json:"procedure_id"`
	Section      string   `json:"section"`
	Excerpt      string   `json:"excerpt"`
	MatchedTerms []string `json:"matched_terms,omitempty"`
}

type KnowledgeEvidence struct {
	EvidenceID       string  `json:"evidence_id"`
	Locator          string  `json:"locator"`
	SourceSnapshotID string  `json:"source_snapshot_id,omitempty"`
	ArtifactKey      string  `json:"artifact_key,omitempty"`
	SourceURI        string  `json:"source_uri,omitempty"`
	SourceVersion    string  `json:"source_version,omitempty"`
	ExtractedText    string  `json:"extracted_text,omitempty"`
	Confidence       float64 `json:"confidence"`
}

type DatasetRequest struct {
	RequestID  string `json:"request_id"`
	ProductID  string `json:"product_id"`
	VehicleKey string `json:"vehicle_key"`
	Status     string `json:"status"`
}

type Entitlement struct {
	EntitlementID    string `json:"entitlement_id"`
	OrganizationID   string `json:"organization_id"`
	DatasetRequestID string `json:"dataset_request_id"`
	Status           string `json:"status"`
}

type Evidence struct {
	EvidenceID       string  `json:"evidence_id"`
	SourceSnapshotID string  `json:"source_snapshot_id"`
	ExtractionRunID  *string `json:"extraction_run_id"`
	Locator          string  `json:"locator"`
	Confidence       float64 `json:"confidence"`
}

type Feedback struct {
	FeedbackID string `json:"feedback_id"`
	DatasetID  string `json:"dataset_id"`
	Category   string `json:"category"`
	Body       string `json:"body"`
}

type Error struct {
	Code      string         `json:"code"`
	Message   string         `json:"message"`
	RequestID string         `json:"request_id"`
	Retryable bool           `json:"retryable"`
	Details   map[string]any `json:"details"`
}

type EventEnvelope struct {
	EventID        string         `json:"event_id"`
	EventType      string         `json:"event_type"`
	EventVersion   int            `json:"event_version"`
	OccurredAt     string         `json:"occurred_at"`
	Producer       string         `json:"producer"`
	RequestID      string         `json:"request_id"`
	ProjectionID   string         `json:"projection_id"`
	RevisionID     *string        `json:"revision_id"`
	CorrelationID  string         `json:"correlation_id"`
	IdempotencyKey string         `json:"idempotency_key"`
	Payload        map[string]any `json:"payload"`
}

type ProcedureStep struct {
	StepNumber        int      `json:"step_number"`
	Instruction       string   `json:"instruction"`
	OperationID       string   `json:"operation_id,omitempty"`
	SourceArticleIDs  []string `json:"source_article_ids"`
	EvidenceIDs       []string `json:"evidence_ids"`
	SafetyWarnings    []string `json:"safety_warnings,omitempty"`
	VisualArtifactIDs []string `json:"visual_artifact_ids,omitempty"`
}

type VisualArtifact struct {
	ArtifactID         string `json:"artifact_id"`
	SourceArtifactID   string `json:"source_artifact_id"`
	SourceArtifactKey  string `json:"source_artifact_key"`
	DerivedArtifactKey string `json:"derived_artifact_key"`
	SourceURI          string `json:"source_uri,omitempty"`
	Processor          string `json:"processor"`
	ProcessorVersion   string `json:"processor_version"`
	ReviewState        string `json:"review_state"`
	Label              string `json:"label,omitempty"`
	PublishedAt        *string `json:"published_at,omitempty"`
}

type PriceSnapshot struct {
	CanonicalPartID  string  `json:"canonical_part_id"`
	SourcePartNumber string  `json:"source_part_number"`
	Amount           float64 `json:"amount"`
	Currency         string  `json:"currency"`
	PricedAt         string  `json:"priced_at"`
	Freshness        string  `json:"freshness"`
	SourceSnapshotID string  `json:"source_snapshot_id"`
	RefreshStatus    string  `json:"refresh_status"`
	MarkupApplied    bool    `json:"markup_applied"`
	SourceURI        string  `json:"source_uri,omitempty"`
}

type ChatQuote struct {
	RequiredHours       float64             `json:"required_hours"`
	RecommendedHours    float64             `json:"recommended_hours"`
	TotalHours          float64             `json:"total_hours"`
	OverlapHoursRemoved float64             `json:"overlap_hours_removed"`
	RequiredOperations  []map[string]any    `json:"required_operations"`
	RecommendedOperations []map[string]any  `json:"recommended_operations"`
	OverlapOperations   []map[string]any    `json:"overlap_operations"`
	Parts               []PriceSnapshot     `json:"parts"`
	Evidence            []KnowledgeEvidence `json:"evidence"`
	Currency            string              `json:"currency,omitempty"`
}

type WorkerProgressEvent struct {
	EventID        string         `json:"event_id"`
	EventType      string         `json:"event_type"`
	EventVersion   int            `json:"event_version"`
	OccurredAt     string         `json:"occurred_at"`
	Producer       string         `json:"producer"`
	RequestID      string         `json:"request_id"`
	ProjectionID   string         `json:"projection_id"`
	RevisionID     *string        `json:"revision_id"`
	CorrelationID  string         `json:"correlation_id"`
	IdempotencyKey string         `json:"idempotency_key"`
	Payload        map[string]any `json:"payload"`
	QueryID        string         `json:"query_id"`
	Stage          string         `json:"stage"`
	Status         string         `json:"status"`
	DataState      string         `json:"data_state"`
	Message        string         `json:"message"`
}

type ChatAnswer struct {
	AnswerStatus    string                `json:"answer_status"`
	DataState       string                `json:"data_state"`
	Vehicle         map[string]any        `json:"vehicle"`
	Procedure       map[string]any        `json:"procedure"`
	Quote           map[string]any        `json:"quote"`
	Warnings        []map[string]any      `json:"warnings"`
	UpdatedAt       string                `json:"updated_at"`
	WorkerStream    []WorkerProgressEvent `json:"worker_stream"`
	SourceWatermark string                `json:"source_watermark,omitempty"`
	RevisionID      *string               `json:"revision_id,omitempty"`
}

type ChatQuery struct {
	QueryID        string          `json:"query_id"`
	ConversationID string          `json:"conversation_id"`
	Message        string          `json:"message"`
	IdempotencyKey string          `json:"idempotency_key"`
	Status         string          `json:"status"`
	VehicleOptions []map[string]any `json:"vehicle_options"`
	Answer         *ChatAnswer     `json:"answer"`
	CorrelationID  string          `json:"correlation_id"`
}

type ChatSelection struct {
	QueryID       string  `json:"query_id"`
	SelectionType string  `json:"selection_type"`
	OptionNumber  *int    `json:"option_number"`
	VehicleID     *string `json:"vehicle_id"`
}
""" % {
        "schema_version": contract["schema_version"],
        "data_state": _go_enum("DataStateValues", contract["data_state"]),
        "answer_status": _go_enum("AnswerStatusValues", contract["answer_status"]),
        "data_state_values": _json_strings(contract["data_state"]),
        "answer_status_values": _json_strings(contract["answer_status"]),
        "dataset_availability": _go_enum("DatasetAvailabilityValues", contract["dataset_availability"]),
        "section_status": _go_enum("SectionStatusValues", contract["section_status"]),
        "event_subjects": _go_enum("EventSubjects", contract["event_subjects"]),
        "knowledge_result_kind": _go_enum("KnowledgeResultKindValues", contract["knowledge_result_kind"]),
        "entitlement_status": _go_enum(
            "EntitlementStatusValues", _enum_values(contract, "entitlement", "status")
        ),
        "feedback_category": _go_enum(
            "FeedbackCategoryValues", _enum_values(contract, "feedback", "category")
        ),
        "error_codes": _go_enum("ErrorCodeValues", _enum_values(contract, "error", "code")),
        **{
            f"{name}_required": _json_strings(contract[name]["required"])
            for name in (
                "dataset_read",
                "knowledge_search_response",
                "knowledge_result",
                "knowledge_article",
                "knowledge_procedure",
                "knowledge_evidence",
                "dataset_request",
                "entitlement",
                "evidence",
                "feedback",
                "error",
                "event_envelope",
                "procedure_step",
                "visual_artifact",
                "price_snapshot",
                "chat_quote",
                "chat_answer",
                "chat_query",
                "chat_selection",
                "worker_progress_event",
            )
        },
    }


def render_python(contract: dict[str, Any]) -> str:
    return """# Code generated by scripts/contracts/generate.py; DO NOT EDIT.
from __future__ import annotations

from dataclasses import dataclass
from typing import Any


SCHEMA_VERSION = %(schema_version)d
DATA_STATE_VALUES = (%(data_state)s,)
ANSWER_STATUS_VALUES = (%(answer_status)s,)
DATASET_AVAILABILITY_VALUES = (%(dataset_availability)s,)
SECTION_STATUS_VALUES = (%(section_status)s,)
EVENT_SUBJECTS = (%(event_subjects)s,)
KNOWLEDGE_RESULT_KIND_VALUES = (%(knowledge_result_kind)s,)
ENTITLEMENT_STATUS_VALUES = (%(entitlement_status)s,)
FEEDBACK_CATEGORY_VALUES = (%(feedback_category)s,)
ERROR_CODE_VALUES = (%(error_codes)s,)
DATASET_READ_REQUIRED_FIELDS = (%(dataset_read_required)s,)
KNOWLEDGE_SEARCH_RESPONSE_REQUIRED_FIELDS = (%(knowledge_search_response_required)s,)
KNOWLEDGE_RESULT_REQUIRED_FIELDS = (%(knowledge_result_required)s,)
KNOWLEDGE_ARTICLE_REQUIRED_FIELDS = (%(knowledge_article_required)s,)
KNOWLEDGE_PROCEDURE_REQUIRED_FIELDS = (%(knowledge_procedure_required)s,)
KNOWLEDGE_EVIDENCE_REQUIRED_FIELDS = (%(knowledge_evidence_required)s,)
DATASET_REQUEST_REQUIRED_FIELDS = (%(dataset_request_required)s,)
ENTITLEMENT_REQUIRED_FIELDS = (%(entitlement_required)s,)
EVIDENCE_REQUIRED_FIELDS = (%(evidence_required)s,)
FEEDBACK_REQUIRED_FIELDS = (%(feedback_required)s,)
ERROR_REQUIRED_FIELDS = (%(error_required)s,)
EVENT_ENVELOPE_REQUIRED_FIELDS = (%(event_envelope_required)s,)
PROCEDURE_STEP_REQUIRED_FIELDS = (%(procedure_step_required)s,)
VISUAL_ARTIFACT_REQUIRED_FIELDS = (%(visual_artifact_required)s,)
PRICE_SNAPSHOT_REQUIRED_FIELDS = (%(price_snapshot_required)s,)
CHAT_QUOTE_REQUIRED_FIELDS = (%(chat_quote_required)s,)
CHAT_ANSWER_REQUIRED_FIELDS = (%(chat_answer_required)s,)
CHAT_QUERY_REQUIRED_FIELDS = (%(chat_query_required)s,)
CHAT_SELECTION_REQUIRED_FIELDS = (%(chat_selection_required)s,)
WORKER_PROGRESS_EVENT_REQUIRED_FIELDS = (%(worker_progress_event_required)s,)


@dataclass(frozen=True)
class DatasetSection:
    name: str
    status: str
    last_published_revision: str | None
    updated_at: str


@dataclass(frozen=True)
class DatasetReadEnvelope:
    dataset_id: str
    revision_id: str
    availability: str
    source_watermark: str
    sections: list[DatasetSection]
    data: dict[str, Any] | None = None
    warnings: list[dict[str, Any]] | None = None


@dataclass(frozen=True)
class KnowledgeSearchResponse:
    dataset_id: str
    revision_id: str
    availability: str
    source_watermark: str
    sections: list[DatasetSection]
    results: list["KnowledgeResult"]
    vehicle_identity: dict[str, Any] | None = None
    fallback_status: str | None = None
    fallback_request_id: str | None = None


@dataclass(frozen=True)
class KnowledgeResult:
    kind: str
    id: str
    score: float
    evidence: list["KnowledgeEvidence"]
    article: "KnowledgeArticle" | None = None
    procedure: "KnowledgeProcedure" | None = None


@dataclass(frozen=True)
class KnowledgeArticle:
    article_id: str
    article_key: str | None = None
    bucket: str | None = None
    title: str | None = None
    bulletin_number: str | None = None
    release_date: str | None = None
    body: str | None = None
    steps: list[Any] | None = None


@dataclass(frozen=True)
class KnowledgeProcedure:
    procedure_id: str
    section: str
    excerpt: str
    matched_terms: list[str] | None = None


@dataclass(frozen=True)
class KnowledgeEvidence:
    evidence_id: str
    locator: str
    confidence: float
    source_snapshot_id: str | None = None
    artifact_key: str | None = None
    source_uri: str | None = None
    source_version: str | None = None
    extracted_text: str | None = None


@dataclass(frozen=True)
class DatasetRequest:
    request_id: str
    product_id: str
    vehicle_key: str
    status: str


@dataclass(frozen=True)
class Entitlement:
    entitlement_id: str
    organization_id: str
    dataset_request_id: str
    status: str


@dataclass(frozen=True)
class Evidence:
    evidence_id: str
    source_snapshot_id: str
    extraction_run_id: str | None
    locator: str
    confidence: float


@dataclass(frozen=True)
class Feedback:
    feedback_id: str
    dataset_id: str
    category: str
    body: str


@dataclass(frozen=True)
class Error:
    code: str
    message: str
    request_id: str
    retryable: bool
    details: dict[str, Any]


@dataclass(frozen=True)
class EventEnvelope:
    event_id: str
    event_type: str
    event_version: int
    occurred_at: str
    producer: str
    request_id: str
    projection_id: str
    revision_id: str | None
    correlation_id: str
    idempotency_key: str
    payload: dict[str, Any]


@dataclass(frozen=True)
class ProcedureStep:
    step_number: int
    instruction: str
    source_article_ids: list[str]
    evidence_ids: list[str]
    operation_id: str | None = None
    safety_warnings: list[str] | None = None
    visual_artifact_ids: list[str] | None = None


@dataclass(frozen=True)
class VisualArtifact:
    artifact_id: str
    source_artifact_id: str
    source_artifact_key: str
    derived_artifact_key: str
    processor: str
    processor_version: str
    review_state: str
    source_uri: str | None = None
    label: str | None = None
    published_at: str | None = None


@dataclass(frozen=True)
class PriceSnapshot:
    canonical_part_id: str
    source_part_number: str
    amount: float
    currency: str
    priced_at: str
    freshness: str
    source_snapshot_id: str
    refresh_status: str
    markup_applied: bool
    source_uri: str | None = None


@dataclass(frozen=True)
class ChatQuote:
    required_hours: float
    recommended_hours: float
    total_hours: float
    overlap_hours_removed: float
    required_operations: list[dict[str, Any]]
    recommended_operations: list[dict[str, Any]]
    overlap_operations: list[dict[str, Any]]
    parts: list[PriceSnapshot]
    evidence: list[KnowledgeEvidence]
    currency: str | None = None


@dataclass(frozen=True)
class WorkerProgressEvent:
    event_id: str
    event_type: str
    event_version: int
    occurred_at: str
    producer: str
    request_id: str
    projection_id: str
    revision_id: str | None
    correlation_id: str
    idempotency_key: str
    payload: dict[str, Any]
    query_id: str
    stage: str
    status: str
    data_state: str
    message: str


@dataclass(frozen=True)
class ChatAnswer:
    answer_status: str
    data_state: str
    vehicle: dict[str, Any]
    procedure: dict[str, Any] | None
    quote: dict[str, Any] | None
    warnings: list[dict[str, Any]]
    updated_at: str
    worker_stream: list[WorkerProgressEvent]
    source_watermark: str | None = None
    revision_id: str | None = None


@dataclass(frozen=True)
class ChatQuery:
    query_id: str
    conversation_id: str
    message: str
    idempotency_key: str
    status: str
    vehicle_options: list[dict[str, Any]]
    answer: ChatAnswer | None
    correlation_id: str


@dataclass(frozen=True)
class ChatSelection:
    query_id: str
    selection_type: str
    option_number: int | None
    vehicle_id: str | None = None
""" % {
        "schema_version": contract["schema_version"],
        "data_state": ", ".join(repr(value) for value in contract["data_state"]),
        "answer_status": ", ".join(repr(value) for value in contract["answer_status"]),
        "dataset_availability": ", ".join(repr(value) for value in contract["dataset_availability"]),
        "section_status": ", ".join(repr(value) for value in contract["section_status"]),
        "event_subjects": ", ".join(repr(value) for value in contract["event_subjects"]),
        "knowledge_result_kind": ", ".join(repr(value) for value in contract["knowledge_result_kind"]),
        "entitlement_status": ", ".join(
            repr(value) for value in _enum_values(contract, "entitlement", "status")
        ),
        "feedback_category": ", ".join(
            repr(value) for value in _enum_values(contract, "feedback", "category")
        ),
        "error_codes": ", ".join(repr(value) for value in _enum_values(contract, "error", "code")),
        **{
            f"{name}_required": ", ".join(repr(value) for value in contract[name]["required"])
            for name in (
                "dataset_read",
                "knowledge_search_response",
                "knowledge_result",
                "knowledge_article",
                "knowledge_procedure",
                "knowledge_evidence",
                "dataset_request",
                "entitlement",
                "evidence",
                "feedback",
                "error",
                "event_envelope",
                "procedure_step",
                "visual_artifact",
                "price_snapshot",
                "chat_quote",
                "chat_answer",
                "chat_query",
                "chat_selection",
                "worker_progress_event",
            )
        },
    }


def main() -> None:
    root = Path(__file__).parents[2]
    contract = load_contract(root / "packages/contracts/contract.json")
    go_path = root / "packages/contracts/go/contracts.go"
    python_path = root / "packages/contracts/python/autodata_contracts/contracts.py"
    write_generated(go_path, render_go(contract))
    write_generated(python_path, render_python(contract))


if __name__ == "__main__":
    main()
