"""Generate Go and Python representations from the canonical contract source."""

from __future__ import annotations

import json
import os
from pathlib import Path
import tempfile
from typing import Any


CONTRACT_NAMES = (
    "dataset_read",
    "dataset_section",
    "dataset_request",
    "entitlement",
    "evidence",
    "feedback",
    "error",
    "event_envelope",
)


def load_contract(path: Path) -> dict[str, Any]:
    contract = json.loads(path.read_text())
    required_top_level = {
        "schema_version",
        "dataset_availability",
        "section_status",
        "event_subjects",
        *CONTRACT_NAMES,
    }
    missing = required_top_level - contract.keys()
    if missing:
        raise ValueError(f"contract is missing top-level keys: {sorted(missing)}")
    if not isinstance(contract["schema_version"], int) or contract["schema_version"] < 1:
        raise ValueError("schema_version must be a positive integer")
    for name in CONTRACT_NAMES:
        definition = contract[name]
        required = definition.get("required")
        properties = definition.get("properties")
        if not isinstance(required, list) or not isinstance(properties, dict):
            raise ValueError(f"{name} must declare required and properties")
        if not set(required).issubset(properties):
            raise ValueError(f"{name} requires an undeclared property")
    return contract


def is_backward_compatible_addition(old: dict[str, Any], new: dict[str, Any]) -> bool:
    """Allow new optional properties while preserving old required behavior."""

    old_required = set(old.get("required", []))
    new_required = set(new.get("required", []))
    old_properties = set(old.get("properties", {}))
    new_properties = set(new.get("properties", {}))
    return old_required == new_required and old_properties.issubset(new_properties)


def write_generated(path: Path, content: str) -> None:
    """Replace generated output atomically so parallel checks never read a partial file."""

    temporary_name: str | None = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w", dir=path.parent, prefix=f".{path.name}.", delete=False
        ) as temporary:
            temporary.write(content)
            temporary_name = temporary.name
        os.replace(temporary_name, path)
        temporary_name = None
    finally:
        if temporary_name:
            Path(temporary_name).unlink(missing_ok=True)


def _json_strings(values: list[str]) -> str:
    return ", ".join(json.dumps(value) for value in values)


def _go_enum(name: str, values: list[str]) -> str:
    return f"var {name} = []string{{{_json_strings(values)}}}\n"


def _enum_values(contract: dict[str, Any], contract_name: str, property_name: str) -> list[str]:
    return contract[contract_name]["properties"][property_name]["enum"]


def render_go(contract: dict[str, Any]) -> str:
    return """// Code generated by scripts/contracts/generate.py; DO NOT EDIT.
package contracts

const SchemaVersion = %(schema_version)d

%(dataset_availability)s%(section_status)s%(event_subjects)s%(entitlement_status)s%(feedback_category)s%(error_codes)s
var DatasetReadRequiredFields = []string{%(dataset_read_required)s}
var DatasetRequestRequiredFields = []string{%(dataset_request_required)s}
var EntitlementRequiredFields = []string{%(entitlement_required)s}
var EvidenceRequiredFields = []string{%(evidence_required)s}
var FeedbackRequiredFields = []string{%(feedback_required)s}
var ErrorRequiredFields = []string{%(error_required)s}
var EventEnvelopeRequiredFields = []string{%(event_envelope_required)s}

type DatasetSection struct {
	Name                  string  `json:"name"`
	Status                string  `json:"status"`
	LastPublishedRevision *string `json:"last_published_revision"`
	UpdatedAt             string  `json:"updated_at"`
}

type DatasetReadEnvelope struct {
	DatasetID       string           `json:"dataset_id"`
	RevisionID      string           `json:"revision_id"`
	Availability    string           `json:"availability"`
	SourceWatermark string           `json:"source_watermark"`
	Sections        []DatasetSection `json:"sections"`
}

type DatasetRequest struct {
	RequestID  string `json:"request_id"`
	ProductID  string `json:"product_id"`
	VehicleKey string `json:"vehicle_key"`
	Status     string `json:"status"`
}

type Entitlement struct {
	EntitlementID    string `json:"entitlement_id"`
	OrganizationID   string `json:"organization_id"`
	DatasetRequestID string `json:"dataset_request_id"`
	Status           string `json:"status"`
}

type Evidence struct {
	EvidenceID       string  `json:"evidence_id"`
	SourceSnapshotID string  `json:"source_snapshot_id"`
	ExtractionRunID  *string `json:"extraction_run_id"`
	Locator          string  `json:"locator"`
	Confidence       float64 `json:"confidence"`
}

type Feedback struct {
	FeedbackID string `json:"feedback_id"`
	DatasetID  string `json:"dataset_id"`
	Category   string `json:"category"`
	Body       string `json:"body"`
}

type Error struct {
	Code      string         `json:"code"`
	Message   string         `json:"message"`
	RequestID string         `json:"request_id"`
	Retryable bool           `json:"retryable"`
	Details   map[string]any `json:"details"`
}

type EventEnvelope struct {
	EventID        string         `json:"event_id"`
	EventType      string         `json:"event_type"`
	EventVersion   int            `json:"event_version"`
	OccurredAt     string         `json:"occurred_at"`
	Producer       string         `json:"producer"`
	RequestID      string         `json:"request_id"`
	ProjectionID   string         `json:"projection_id"`
	RevisionID     *string        `json:"revision_id"`
	CorrelationID  string         `json:"correlation_id"`
	IdempotencyKey string         `json:"idempotency_key"`
	Payload        map[string]any `json:"payload"`
}
""" % {
        "schema_version": contract["schema_version"],
        "dataset_availability": _go_enum("DatasetAvailabilityValues", contract["dataset_availability"]),
        "section_status": _go_enum("SectionStatusValues", contract["section_status"]),
        "event_subjects": _go_enum("EventSubjects", contract["event_subjects"]),
        "entitlement_status": _go_enum(
            "EntitlementStatusValues", _enum_values(contract, "entitlement", "status")
        ),
        "feedback_category": _go_enum(
            "FeedbackCategoryValues", _enum_values(contract, "feedback", "category")
        ),
        "error_codes": _go_enum("ErrorCodeValues", _enum_values(contract, "error", "code")),
        **{
            f"{name}_required": _json_strings(contract[name]["required"])
            for name in (
                "dataset_read",
                "dataset_request",
                "entitlement",
                "evidence",
                "feedback",
                "error",
                "event_envelope",
            )
        },
    }


def render_python(contract: dict[str, Any]) -> str:
    return """# Code generated by scripts/contracts/generate.py; DO NOT EDIT.
from dataclasses import dataclass
from typing import Any


SCHEMA_VERSION = %(schema_version)d
DATASET_AVAILABILITY_VALUES = (%(dataset_availability)s,)
SECTION_STATUS_VALUES = (%(section_status)s,)
EVENT_SUBJECTS = (%(event_subjects)s,)
ENTITLEMENT_STATUS_VALUES = (%(entitlement_status)s,)
FEEDBACK_CATEGORY_VALUES = (%(feedback_category)s,)
ERROR_CODE_VALUES = (%(error_codes)s,)
DATASET_READ_REQUIRED_FIELDS = (%(dataset_read_required)s,)
DATASET_REQUEST_REQUIRED_FIELDS = (%(dataset_request_required)s,)
ENTITLEMENT_REQUIRED_FIELDS = (%(entitlement_required)s,)
EVIDENCE_REQUIRED_FIELDS = (%(evidence_required)s,)
FEEDBACK_REQUIRED_FIELDS = (%(feedback_required)s,)
ERROR_REQUIRED_FIELDS = (%(error_required)s,)
EVENT_ENVELOPE_REQUIRED_FIELDS = (%(event_envelope_required)s,)


@dataclass(frozen=True)
class DatasetSection:
    name: str
    status: str
    last_published_revision: str | None
    updated_at: str


@dataclass(frozen=True)
class DatasetReadEnvelope:
    dataset_id: str
    revision_id: str
    availability: str
    source_watermark: str
    sections: list[DatasetSection]
    data: dict[str, Any] | None = None
    warnings: list[dict[str, Any]] | None = None


@dataclass(frozen=True)
class DatasetRequest:
    request_id: str
    product_id: str
    vehicle_key: str
    status: str


@dataclass(frozen=True)
class Entitlement:
    entitlement_id: str
    organization_id: str
    dataset_request_id: str
    status: str


@dataclass(frozen=True)
class Evidence:
    evidence_id: str
    source_snapshot_id: str
    extraction_run_id: str | None
    locator: str
    confidence: float


@dataclass(frozen=True)
class Feedback:
    feedback_id: str
    dataset_id: str
    category: str
    body: str


@dataclass(frozen=True)
class Error:
    code: str
    message: str
    request_id: str
    retryable: bool
    details: dict[str, Any]


@dataclass(frozen=True)
class EventEnvelope:
    event_id: str
    event_type: str
    event_version: int
    occurred_at: str
    producer: str
    request_id: str
    projection_id: str
    revision_id: str | None
    correlation_id: str
    idempotency_key: str
    payload: dict[str, Any]
""" % {
        "schema_version": contract["schema_version"],
        "dataset_availability": ", ".join(repr(value) for value in contract["dataset_availability"]),
        "section_status": ", ".join(repr(value) for value in contract["section_status"]),
        "event_subjects": ", ".join(repr(value) for value in contract["event_subjects"]),
        "entitlement_status": ", ".join(
            repr(value) for value in _enum_values(contract, "entitlement", "status")
        ),
        "feedback_category": ", ".join(
            repr(value) for value in _enum_values(contract, "feedback", "category")
        ),
        "error_codes": ", ".join(repr(value) for value in _enum_values(contract, "error", "code")),
        **{
            f"{name}_required": ", ".join(repr(value) for value in contract[name]["required"])
            for name in (
                "dataset_read",
                "dataset_request",
                "entitlement",
                "evidence",
                "feedback",
                "error",
                "event_envelope",
            )
        },
    }


def main() -> None:
    root = Path(__file__).parents[2]
    contract = load_contract(root / "packages/contracts/contract.json")
    go_path = root / "packages/contracts/go/contracts.go"
    python_path = root / "packages/contracts/python/autodata_contracts/contracts.py"
    write_generated(go_path, render_go(contract))
    write_generated(python_path, render_python(contract))


if __name__ == "__main__":
    main()
