// Code generated by scripts/contracts/generate.py; DO NOT EDIT.
package contracts

const SchemaVersion = 1

var DatasetAvailabilityValues = []string{"purchased", "fast_lane_processing", "viewable", "enriching", "complete", "failed", "needs_review", "revoked"}
var SectionStatusValues = []string{"pending", "processing", "viewable", "complete", "failed", "needs_review"}
var EventSubjects = []string{"dataset.fast.requested", "dataset.viewable", "dataset.deep.requested", "dataset.section.published", "dataset.enrichment.failed", "dataset.review.requested", "dataset.revision.revoked"}
var EntitlementStatusValues = []string{"active", "revoked"}
var FeedbackCategoryValues = []string{"correction", "missing", "quality", "safety"}
var ErrorCodeValues = []string{"UNAUTHENTICATED", "ENTITLEMENT_REQUIRED", "ENTITLEMENT_REVOKED", "DATASET_NOT_VIEWABLE", "SECTION_FAILED", "REVISION_NOT_FOUND", "DUPLICATE_REQUEST", "INVALID_EVIDENCE", "REVIEW_REQUIRED"}

var DatasetReadRequiredFields = []string{"dataset_id", "revision_id", "availability", "source_watermark", "sections"}
var DatasetRequestRequiredFields = []string{"request_id", "product_id", "vehicle_key", "status"}
var EntitlementRequiredFields = []string{"entitlement_id", "organization_id", "dataset_request_id", "status"}
var EvidenceRequiredFields = []string{"evidence_id", "source_snapshot_id", "extraction_run_id", "locator", "confidence"}
var FeedbackRequiredFields = []string{"feedback_id", "dataset_id", "category", "body"}
var ErrorRequiredFields = []string{"code", "message", "request_id", "retryable", "details"}
var EventEnvelopeRequiredFields = []string{"event_id", "event_type", "event_version", "occurred_at", "producer", "request_id", "projection_id", "revision_id", "correlation_id", "idempotency_key", "payload"}

type DatasetSection struct {
	Name                  string  `json:"name"`
	Status                string  `json:"status"`
	LastPublishedRevision *string `json:"last_published_revision"`
	UpdatedAt             string  `json:"updated_at"`
}

type DatasetReadEnvelope struct {
	DatasetID       string           `json:"dataset_id"`
	RevisionID      string           `json:"revision_id"`
	Availability    string           `json:"availability"`
	SourceWatermark string           `json:"source_watermark"`
	Sections        []DatasetSection `json:"sections"`
}

type DatasetRequest struct {
	RequestID  string `json:"request_id"`
	ProductID  string `json:"product_id"`
	VehicleKey string `json:"vehicle_key"`
	Status     string `json:"status"`
}

type Entitlement struct {
	EntitlementID    string `json:"entitlement_id"`
	OrganizationID   string `json:"organization_id"`
	DatasetRequestID string `json:"dataset_request_id"`
	Status           string `json:"status"`
}

type Evidence struct {
	EvidenceID       string  `json:"evidence_id"`
	SourceSnapshotID string  `json:"source_snapshot_id"`
	ExtractionRunID  *string `json:"extraction_run_id"`
	Locator          string  `json:"locator"`
	Confidence       float64 `json:"confidence"`
}

type Feedback struct {
	FeedbackID string `json:"feedback_id"`
	DatasetID  string `json:"dataset_id"`
	Category   string `json:"category"`
	Body       string `json:"body"`
}

type Error struct {
	Code      string         `json:"code"`
	Message   string         `json:"message"`
	RequestID string         `json:"request_id"`
	Retryable bool           `json:"retryable"`
	Details   map[string]any `json:"details"`
}

type EventEnvelope struct {
	EventID        string         `json:"event_id"`
	EventType      string         `json:"event_type"`
	EventVersion   int            `json:"event_version"`
	OccurredAt     string         `json:"occurred_at"`
	Producer       string         `json:"producer"`
	RequestID      string         `json:"request_id"`
	ProjectionID   string         `json:"projection_id"`
	RevisionID     *string        `json:"revision_id"`
	CorrelationID  string         `json:"correlation_id"`
	IdempotencyKey string         `json:"idempotency_key"`
	Payload        map[string]any `json:"payload"`
}
