// Code generated by scripts/contracts/generate.py; DO NOT EDIT.
package contracts

const SchemaVersion = 1

var DataStateValues = []string{"normalized", "source_unnormalized", "stale", "normalizing", "mixed", "unavailable", "needs_review"}
var AnswerStatusValues = []string{"options", "processing", "available", "partial", "complete", "failed", "needs_review"}
var DatasetAvailabilityValues = []string{"purchased", "fast_lane_processing", "viewable", "enriching", "complete", "failed", "needs_review", "revoked"}
var SectionStatusValues = []string{"pending", "processing", "viewable", "complete", "failed", "needs_review"}
var EventSubjects = []string{"dataset.fast.requested", "dataset.viewable", "dataset.deep.requested", "dataset.knowledge.fallback.requested", "dataset.section.published", "dataset.enrichment.failed", "dataset.review.requested", "dataset.revision.revoked", "chat.answer.updated", "chat.vehicle.options", "chat.worker.progress", "chat.price.refresh.requested", "chat.procedure.published", "chat.visual.published"}
var KnowledgeResultKindValues = []string{"article", "procedure"}
var EntitlementStatusValues = []string{"active", "revoked"}
var FeedbackCategoryValues = []string{"correction", "missing", "quality", "safety"}
var ErrorCodeValues = []string{"UNAUTHENTICATED", "ENTITLEMENT_REQUIRED", "FORBIDDEN", "ENTITLEMENT_REVOKED", "DATASET_NOT_VIEWABLE", "SECTION_FAILED", "REVISION_NOT_FOUND", "DUPLICATE_REQUEST", "INVALID_EVIDENCE", "REVIEW_REQUIRED", "SOURCE_REVIEW_NOT_FOUND", "SOURCE_REVIEW_CONFLICT", "INGESTION_UNAVAILABLE", "INVALID_REQUEST"}

var DatasetReadRequiredFields = []string{"dataset_id", "revision_id", "availability", "source_watermark", "sections"}
var KnowledgeSearchResponseRequiredFields = []string{"dataset_id", "revision_id", "availability", "source_watermark", "sections", "results"}
var KnowledgeResultRequiredFields = []string{"kind", "id", "score", "evidence"}
var KnowledgeArticleRequiredFields = []string{"article_id"}
var KnowledgeProcedureRequiredFields = []string{"procedure_id", "section", "excerpt"}
var KnowledgeEvidenceRequiredFields = []string{"evidence_id", "locator", "confidence"}
var DatasetRequestRequiredFields = []string{"request_id", "product_id", "vehicle_key", "status"}
var EntitlementRequiredFields = []string{"entitlement_id", "organization_id", "dataset_request_id", "status"}
var EvidenceRequiredFields = []string{"evidence_id", "source_snapshot_id", "extraction_run_id", "locator", "confidence"}
var FeedbackRequiredFields = []string{"feedback_id", "dataset_id", "category", "body"}
var ErrorRequiredFields = []string{"code", "message", "request_id", "retryable", "details"}
var EventEnvelopeRequiredFields = []string{"event_id", "event_type", "event_version", "occurred_at", "producer", "request_id", "projection_id", "revision_id", "correlation_id", "idempotency_key", "payload"}
var ProcedureStepRequiredFields = []string{"step_number", "instruction", "source_article_ids", "evidence_ids"}
var VisualArtifactRequiredFields = []string{"artifact_id", "source_artifact_id", "source_artifact_key", "derived_artifact_key", "processor", "processor_version", "review_state"}
var PriceSnapshotRequiredFields = []string{"canonical_part_id", "source_part_number", "amount", "currency", "priced_at", "freshness", "source_snapshot_id", "refresh_status", "markup_applied"}
var ChatQuoteRequiredFields = []string{"required_hours", "recommended_hours", "total_hours", "overlap_hours_removed", "required_operations", "recommended_operations", "overlap_operations", "parts", "evidence"}
var ChatAnswerRequiredFields = []string{"answer_status", "data_state", "vehicle", "procedure", "quote", "warnings", "updated_at", "worker_stream"}
var ChatQueryRequiredFields = []string{"query_id", "conversation_id", "message", "idempotency_key", "status", "vehicle_options", "answer", "correlation_id"}
var ChatSelectionRequiredFields = []string{"query_id", "selection_type", "option_number"}
var WorkerProgressEventRequiredFields = []string{"event_id", "event_type", "event_version", "occurred_at", "producer", "request_id", "projection_id", "revision_id", "correlation_id", "idempotency_key", "payload", "query_id", "stage", "status", "data_state", "message"}

type DatasetSection struct {
	Name                  string  `json:"name"`
	Status                string  `json:"status"`
	LastPublishedRevision *string `json:"last_published_revision"`
	UpdatedAt             string  `json:"updated_at"`
}

type DatasetReadEnvelope struct {
	DatasetID       string           `json:"dataset_id"`
	RevisionID      string           `json:"revision_id"`
	Availability    string           `json:"availability"`
	SourceWatermark string           `json:"source_watermark"`
	Sections        []DatasetSection `json:"sections"`
}

type KnowledgeSearchResponse struct {
	DatasetID       string                 `json:"dataset_id"`
	RevisionID      string                 `json:"revision_id"`
	Availability    string                 `json:"availability"`
	SourceWatermark string                 `json:"source_watermark"`
	Sections        []DatasetSection       `json:"sections"`
	VehicleIdentity map[string]any         `json:"vehicle_identity,omitempty"`
	FallbackStatus   string                 `json:"fallback_status,omitempty"`
	FallbackRequestID string                `json:"fallback_request_id,omitempty"`
	Results         []KnowledgeResult      `json:"results"`
}

type KnowledgeResult struct {
	Kind      string             `json:"kind"`
	ID        string             `json:"id"`
	Score     float64            `json:"score"`
	Article   *KnowledgeArticle  `json:"article,omitempty"`
	Procedure *KnowledgeProcedure `json:"procedure,omitempty"`
	Evidence  []KnowledgeEvidence `json:"evidence"`
}

type KnowledgeArticle struct {
	ArticleID      string `json:"article_id"`
	ArticleKey     string `json:"article_key,omitempty"`
	Bucket         string `json:"bucket,omitempty"`
	Title          string `json:"title,omitempty"`
	BulletinNumber string `json:"bulletin_number,omitempty"`
	ReleaseDate    string `json:"release_date,omitempty"`
	Body           string `json:"body,omitempty"`
	Steps          []any  `json:"steps,omitempty"`
}

type KnowledgeProcedure struct {
	ProcedureID  string   `json:"procedure_id"`
	Section      string   `json:"section"`
	Excerpt      string   `json:"excerpt"`
	MatchedTerms []string `json:"matched_terms,omitempty"`
}

type KnowledgeEvidence struct {
	EvidenceID       string  `json:"evidence_id"`
	Locator          string  `json:"locator"`
	SourceSnapshotID string  `json:"source_snapshot_id,omitempty"`
	ArtifactKey      string  `json:"artifact_key,omitempty"`
	SourceURI        string  `json:"source_uri,omitempty"`
	SourceVersion    string  `json:"source_version,omitempty"`
	ExtractedText    string  `json:"extracted_text,omitempty"`
	Confidence       float64 `json:"confidence"`
}

type DatasetRequest struct {
	RequestID  string `json:"request_id"`
	ProductID  string `json:"product_id"`
	VehicleKey string `json:"vehicle_key"`
	Status     string `json:"status"`
}

type Entitlement struct {
	EntitlementID    string `json:"entitlement_id"`
	OrganizationID   string `json:"organization_id"`
	DatasetRequestID string `json:"dataset_request_id"`
	Status           string `json:"status"`
}

type Evidence struct {
	EvidenceID       string  `json:"evidence_id"`
	SourceSnapshotID string  `json:"source_snapshot_id"`
	ExtractionRunID  *string `json:"extraction_run_id"`
	Locator          string  `json:"locator"`
	Confidence       float64 `json:"confidence"`
}

type Feedback struct {
	FeedbackID string `json:"feedback_id"`
	DatasetID  string `json:"dataset_id"`
	Category   string `json:"category"`
	Body       string `json:"body"`
}

type Error struct {
	Code      string         `json:"code"`
	Message   string         `json:"message"`
	RequestID string         `json:"request_id"`
	Retryable bool           `json:"retryable"`
	Details   map[string]any `json:"details"`
}

type EventEnvelope struct {
	EventID        string         `json:"event_id"`
	EventType      string         `json:"event_type"`
	EventVersion   int            `json:"event_version"`
	OccurredAt     string         `json:"occurred_at"`
	Producer       string         `json:"producer"`
	RequestID      string         `json:"request_id"`
	ProjectionID   string         `json:"projection_id"`
	RevisionID     *string        `json:"revision_id"`
	CorrelationID  string         `json:"correlation_id"`
	IdempotencyKey string         `json:"idempotency_key"`
	Payload        map[string]any `json:"payload"`
}

type ProcedureStep struct {
	StepNumber        int      `json:"step_number"`
	Instruction       string   `json:"instruction"`
	OperationID       string   `json:"operation_id,omitempty"`
	SourceArticleIDs  []string `json:"source_article_ids"`
	EvidenceIDs       []string `json:"evidence_ids"`
	SafetyWarnings    []string `json:"safety_warnings,omitempty"`
	VisualArtifactIDs []string `json:"visual_artifact_ids,omitempty"`
}

type VisualArtifact struct {
	ArtifactID         string `json:"artifact_id"`
	SourceArtifactID   string `json:"source_artifact_id"`
	SourceArtifactKey  string `json:"source_artifact_key"`
	DerivedArtifactKey string `json:"derived_artifact_key"`
	SourceURI          string `json:"source_uri,omitempty"`
	Processor          string `json:"processor"`
	ProcessorVersion   string `json:"processor_version"`
	ReviewState        string `json:"review_state"`
	Label              string `json:"label,omitempty"`
	PublishedAt        *string `json:"published_at,omitempty"`
}

type PriceSnapshot struct {
	CanonicalPartID  string  `json:"canonical_part_id"`
	SourcePartNumber string  `json:"source_part_number"`
	Amount           float64 `json:"amount"`
	Currency         string  `json:"currency"`
	PricedAt         string  `json:"priced_at"`
	Freshness        string  `json:"freshness"`
	SourceSnapshotID string  `json:"source_snapshot_id"`
	RefreshStatus    string  `json:"refresh_status"`
	MarkupApplied    bool    `json:"markup_applied"`
	SourceURI        string  `json:"source_uri,omitempty"`
}

type ChatQuote struct {
	RequiredHours       float64             `json:"required_hours"`
	RecommendedHours    float64             `json:"recommended_hours"`
	TotalHours          float64             `json:"total_hours"`
	OverlapHoursRemoved float64             `json:"overlap_hours_removed"`
	RequiredOperations  []map[string]any    `json:"required_operations"`
	RecommendedOperations []map[string]any  `json:"recommended_operations"`
	OverlapOperations   []map[string]any    `json:"overlap_operations"`
	Parts               []PriceSnapshot     `json:"parts"`
	Evidence            []KnowledgeEvidence `json:"evidence"`
	Currency            string              `json:"currency,omitempty"`
}

type WorkerProgressEvent struct {
	EventID        string         `json:"event_id"`
	EventType      string         `json:"event_type"`
	EventVersion   int            `json:"event_version"`
	OccurredAt     string         `json:"occurred_at"`
	Producer       string         `json:"producer"`
	RequestID      string         `json:"request_id"`
	ProjectionID   string         `json:"projection_id"`
	RevisionID     *string        `json:"revision_id"`
	CorrelationID  string         `json:"correlation_id"`
	IdempotencyKey string         `json:"idempotency_key"`
	Payload        map[string]any `json:"payload"`
	QueryID        string         `json:"query_id"`
	Stage          string         `json:"stage"`
	Status         string         `json:"status"`
	DataState      string         `json:"data_state"`
	Message        string         `json:"message"`
}

type ChatAnswer struct {
	AnswerStatus    string                `json:"answer_status"`
	DataState       string                `json:"data_state"`
	Vehicle         map[string]any        `json:"vehicle"`
	Procedure       map[string]any        `json:"procedure"`
	Quote           map[string]any        `json:"quote"`
	Warnings        []map[string]any      `json:"warnings"`
	UpdatedAt       string                `json:"updated_at"`
	WorkerStream    []WorkerProgressEvent `json:"worker_stream"`
	SourceWatermark string                `json:"source_watermark,omitempty"`
	RevisionID      *string               `json:"revision_id,omitempty"`
}

type ChatQuery struct {
	QueryID        string          `json:"query_id"`
	ConversationID string          `json:"conversation_id"`
	Message        string          `json:"message"`
	IdempotencyKey string          `json:"idempotency_key"`
	Status         string          `json:"status"`
	VehicleOptions []map[string]any `json:"vehicle_options"`
	Answer         *ChatAnswer     `json:"answer"`
	CorrelationID  string          `json:"correlation_id"`
}

type ChatSelection struct {
	QueryID       string  `json:"query_id"`
	SelectionType string  `json:"selection_type"`
	OptionNumber  *int    `json:"option_number"`
	VehicleID     *string `json:"vehicle_id"`
}
