# Code generated by scripts/contracts/generate.py; DO NOT EDIT.
from dataclasses import dataclass
from typing import Any


SCHEMA_VERSION = 1
DATASET_AVAILABILITY_VALUES = ('purchased', 'fast_lane_processing', 'viewable', 'enriching', 'complete', 'failed', 'needs_review', 'revoked',)
SECTION_STATUS_VALUES = ('pending', 'processing', 'viewable', 'complete', 'failed', 'needs_review',)
EVENT_SUBJECTS = ('dataset.fast.requested', 'dataset.viewable', 'dataset.deep.requested', 'dataset.section.published', 'dataset.enrichment.failed', 'dataset.review.requested', 'dataset.revision.revoked',)
ENTITLEMENT_STATUS_VALUES = ('active', 'revoked',)
FEEDBACK_CATEGORY_VALUES = ('correction', 'missing', 'quality', 'safety',)
ERROR_CODE_VALUES = ('UNAUTHENTICATED', 'ENTITLEMENT_REQUIRED', 'FORBIDDEN', 'ENTITLEMENT_REVOKED', 'DATASET_NOT_VIEWABLE', 'SECTION_FAILED', 'REVISION_NOT_FOUND', 'DUPLICATE_REQUEST', 'INVALID_EVIDENCE', 'REVIEW_REQUIRED', 'INVALID_REQUEST',)
DATASET_READ_REQUIRED_FIELDS = ('dataset_id', 'revision_id', 'availability', 'source_watermark', 'sections',)
DATASET_REQUEST_REQUIRED_FIELDS = ('request_id', 'product_id', 'vehicle_key', 'status',)
ENTITLEMENT_REQUIRED_FIELDS = ('entitlement_id', 'organization_id', 'dataset_request_id', 'status',)
EVIDENCE_REQUIRED_FIELDS = ('evidence_id', 'source_snapshot_id', 'extraction_run_id', 'locator', 'confidence',)
FEEDBACK_REQUIRED_FIELDS = ('feedback_id', 'dataset_id', 'category', 'body',)
ERROR_REQUIRED_FIELDS = ('code', 'message', 'request_id', 'retryable', 'details',)
EVENT_ENVELOPE_REQUIRED_FIELDS = ('event_id', 'event_type', 'event_version', 'occurred_at', 'producer', 'request_id', 'projection_id', 'revision_id', 'correlation_id', 'idempotency_key', 'payload',)


@dataclass(frozen=True)
class DatasetSection:
    name: str
    status: str
    last_published_revision: str | None
    updated_at: str


@dataclass(frozen=True)
class DatasetReadEnvelope:
    dataset_id: str
    revision_id: str
    availability: str
    source_watermark: str
    sections: list[DatasetSection]
    data: dict[str, Any] | None = None
    warnings: list[dict[str, Any]] | None = None


@dataclass(frozen=True)
class DatasetRequest:
    request_id: str
    product_id: str
    vehicle_key: str
    status: str


@dataclass(frozen=True)
class Entitlement:
    entitlement_id: str
    organization_id: str
    dataset_request_id: str
    status: str


@dataclass(frozen=True)
class Evidence:
    evidence_id: str
    source_snapshot_id: str
    extraction_run_id: str | None
    locator: str
    confidence: float


@dataclass(frozen=True)
class Feedback:
    feedback_id: str
    dataset_id: str
    category: str
    body: str


@dataclass(frozen=True)
class Error:
    code: str
    message: str
    request_id: str
    retryable: bool
    details: dict[str, Any]


@dataclass(frozen=True)
class EventEnvelope:
    event_id: str
    event_type: str
    event_version: int
    occurred_at: str
    producer: str
    request_id: str
    projection_id: str
    revision_id: str | None
    correlation_id: str
    idempotency_key: str
    payload: dict[str, Any]
