package main

import (
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
)

func TestDashboardRouteServesChatbotShell(t *testing.T) {
	server := NewServerWithDependencies(staticReadiness{}, &fakeAuthenticator{err: ErrUnauthenticated}, newMemoryRequestStore())
	request := httptest.NewRequest(http.MethodGet, "/dashboard/", nil)
	response := httptest.NewRecorder()

	server.Handler().ServeHTTP(response, request)

	if response.Code != http.StatusOK {
		t.Fatalf("status = %d, want %d", response.Code, http.StatusOK)
	}
	if response.Header().Get("Cache-Control") != "no-cache" {
		t.Fatalf("cache control = %q, want no-cache", response.Header().Get("Cache-Control"))
	}
	body := response.Body.String()
	for _, marker := range []string{
		"AutoData service bay",
		"Natural-language repair intelligence",
		"Natural-language repair request",
		"class=\"panel answer-panel\"",
		"id=\"vehicle-options\"",
		"id=\"procedure-steps\"",
		"id=\"procedure-html\"",
		`Open complete guide as HTML in a new window`,
		`Open complete guide as PDF in a new window`,
		`target="_blank"`,
		`rel="noopener noreferrer"`,
		`data-guide-artifact="html"`,
		`data-guide-artifact="pdf"`,
		`/dashboard/app.js?v=procedure-window-auth-v4`,
		"id=\"parts-list\"",
		"id=\"worker-terminal\"",
		"id=\"consumer-summary\"",
		"id=\"detail-toggle\"",
		"Detailed view",
		"data-detail-view=\"compact\"",
		"/dashboard/app.js",
	} {
		if !strings.Contains(body, marker) {
			t.Fatalf("dashboard body does not contain %q", marker)
		}
	}
	for _, forbidden := range []string{
		`id="year"`,
		`id="make"`,
		`id="model"`,
		`id="engine"`,
		`id="drivetrain"`,
		"<select",
	} {
		if strings.Contains(body, forbidden) {
			t.Fatalf("dashboard still contains a required vehicle selector %q", forbidden)
		}
	}
	if strings.Contains(body, `download="autodata-repair-guide`) {
		t.Fatal("dashboard guide actions must render in a new window, not force downloads")
	}
}

func TestDashboardRouteRedirectsMissingTrailingSlash(t *testing.T) {
	server := NewServerWithDependencies(staticReadiness{}, &fakeAuthenticator{err: ErrUnauthenticated}, newMemoryRequestStore())
	request := httptest.NewRequest(http.MethodGet, "/dashboard", nil)
	response := httptest.NewRecorder()

	server.Handler().ServeHTTP(response, request)

	if response.Code != http.StatusMovedPermanently {
		t.Fatalf("status = %d, want %d", response.Code, http.StatusMovedPermanently)
	}
	if location := response.Header().Get("Location"); location != "/dashboard/" {
		t.Fatalf("location = %q, want /dashboard/", location)
	}
}

func TestDashboardRouteServesJavaScriptAsset(t *testing.T) {
	server := NewServerWithDependencies(staticReadiness{}, &fakeAuthenticator{err: ErrUnauthenticated}, newMemoryRequestStore())
	request := httptest.NewRequest(http.MethodGet, "/dashboard/app.js", nil)
	response := httptest.NewRecorder()

	server.Handler().ServeHTTP(response, request)

	if response.Code != http.StatusOK {
		t.Fatalf("status = %d, want %d", response.Code, http.StatusOK)
	}
	if response.Header().Get("Cache-Control") != "no-cache" {
		t.Fatalf("cache control = %q, want no-cache", response.Header().Get("Cache-Control"))
	}
	body := response.Body.String()
	for _, marker := range []string{
		`query: "/chat/queries"`,
		"/selections",
		"/events",
		"vehicle_options",
		"dataset.optionNumber",
		"option_number",
		"source_unnormalized",
		`freshness.toLowerCase() === "stale"`,
		"priced_at",
		"required_hours",
		"recommended_hours",
		"Generated by",
		"answer.html",
		"procedure-html",
		`target = "_blank"`,
		`rel = "noopener noreferrer"`,
		`window.open("about:blank", "_blank")`,
		"fetchGuideInNewWindow",
		"artifactLink.click()",
		"URL.createObjectURL",
		"preloadGuideArtifact",
		"openCachedGuideInNewWindow",
		"guideWindow.document.write",
		`querySelectorAll("a[data-guide-artifact]")`,
		"UNREVIEWED",
		"worker_stream",
		"renderConsumerSummary",
		"if (options.length && !answer.procedure && !answer.quote && !answer.labor)",
		"Matched vehicle. The procedure and quote are shown below.",
		"detailView",
		"technical-only",
		`Accept: "text/event-stream"`,
		`headers["Last-Event-ID"]`,
		"refreshQueryAfterStream",
		"const durableRefresh = refreshQueryAfterStream(queryId)",
		"void openEventStream(state.queryId)",
		"const maxAttempts = 120",
		"job-plans",
	} {
		if !strings.Contains(body, marker) {
			t.Fatalf("dashboard JavaScript does not contain %q", marker)
		}
	}
	if strings.Contains(body, "slice(0, 4)") {
		t.Fatal("dashboard JavaScript must not truncate compiled procedures")
	}
}

func TestDashboardRouteServesWorkerAndAnswerStyles(t *testing.T) {
	server := NewServerWithDependencies(staticReadiness{}, &fakeAuthenticator{err: ErrUnauthenticated}, newMemoryRequestStore())
	request := httptest.NewRequest(http.MethodGet, "/dashboard/styles.css", nil)
	response := httptest.NewRecorder()

	server.Handler().ServeHTTP(response, request)

	if response.Code != http.StatusOK {
		t.Fatalf("status = %d, want %d", response.Code, http.StatusOK)
	}
	body := response.Body.String()
	for _, marker := range []string{".workers-terminal", ".option-button", ".answer-grid", "prefers-reduced-motion"} {
		if !strings.Contains(body, marker) {
			t.Fatalf("dashboard CSS does not contain %q", marker)
		}
	}
}
