package main

import (
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
)

func TestDashboardRouteServesChatbotShell(t *testing.T) {
	server := NewServerWithDependencies(staticReadiness{}, &fakeAuthenticator{err: ErrUnauthenticated}, newMemoryRequestStore())
	request := httptest.NewRequest(http.MethodGet, "/dashboard/", nil)
	response := httptest.NewRecorder()

	server.Handler().ServeHTTP(response, request)

	if response.Code != http.StatusOK {
		t.Fatalf("status = %d, want %d", response.Code, http.StatusOK)
	}
	body := response.Body.String()
	for _, marker := range []string{
		"AutoData service bay",
		"Natural-language repair intelligence",
		"Natural-language repair request",
		"class=\"panel answer-panel\"",
		"id=\"vehicle-options\"",
		"id=\"procedure-steps\"",
		"id=\"parts-list\"",
		"id=\"worker-terminal\"",
		"/dashboard/app.js",
	} {
		if !strings.Contains(body, marker) {
			t.Fatalf("dashboard body does not contain %q", marker)
		}
	}
	for _, forbidden := range []string{
		`id="year"`,
		`id="make"`,
		`id="model"`,
		`id="engine"`,
		`id="drivetrain"`,
		"<select",
	} {
		if strings.Contains(body, forbidden) {
			t.Fatalf("dashboard still contains a required vehicle selector %q", forbidden)
		}
	}
}

func TestDashboardRouteRedirectsMissingTrailingSlash(t *testing.T) {
	server := NewServerWithDependencies(staticReadiness{}, &fakeAuthenticator{err: ErrUnauthenticated}, newMemoryRequestStore())
	request := httptest.NewRequest(http.MethodGet, "/dashboard", nil)
	response := httptest.NewRecorder()

	server.Handler().ServeHTTP(response, request)

	if response.Code != http.StatusMovedPermanently {
		t.Fatalf("status = %d, want %d", response.Code, http.StatusMovedPermanently)
	}
	if location := response.Header().Get("Location"); location != "/dashboard/" {
		t.Fatalf("location = %q, want /dashboard/", location)
	}
}

func TestDashboardRouteServesJavaScriptAsset(t *testing.T) {
	server := NewServerWithDependencies(staticReadiness{}, &fakeAuthenticator{err: ErrUnauthenticated}, newMemoryRequestStore())
	request := httptest.NewRequest(http.MethodGet, "/dashboard/app.js", nil)
	response := httptest.NewRecorder()

	server.Handler().ServeHTTP(response, request)

	if response.Code != http.StatusOK {
		t.Fatalf("status = %d, want %d", response.Code, http.StatusOK)
	}
	body := response.Body.String()
	for _, marker := range []string{
		`query: "/chat/queries"`,
		"/selections",
		"/events",
		"vehicle_options",
		"dataset.optionNumber",
		"option_number",
		"source_unnormalized",
		`freshness.toLowerCase() === "stale"`,
		"priced_at",
		"required_hours",
		"recommended_hours",
		"Generated by",
		"UNREVIEWED",
		"worker_stream",
		`Accept: "text/event-stream"`,
		`headers["Last-Event-ID"]`,
		"job-plans",
	} {
		if !strings.Contains(body, marker) {
			t.Fatalf("dashboard JavaScript does not contain %q", marker)
		}
	}
	if strings.Contains(body, "slice(0, 4)") {
		t.Fatal("dashboard JavaScript must not truncate compiled procedures")
	}
}

func TestDashboardRouteServesWorkerAndAnswerStyles(t *testing.T) {
	server := NewServerWithDependencies(staticReadiness{}, &fakeAuthenticator{err: ErrUnauthenticated}, newMemoryRequestStore())
	request := httptest.NewRequest(http.MethodGet, "/dashboard/styles.css", nil)
	response := httptest.NewRecorder()

	server.Handler().ServeHTTP(response, request)

	if response.Code != http.StatusOK {
		t.Fatalf("status = %d, want %d", response.Code, http.StatusOK)
	}
	body := response.Body.String()
	for _, marker := range []string{".workers-terminal", ".option-button", ".answer-grid", "prefers-reduced-motion"} {
		if !strings.Contains(body, marker) {
			t.Fatalf("dashboard CSS does not contain %q", marker)
		}
	}
}
