#!/usr/bin/env python3
"""Review the AutoData chat experience from a consumer's point of view.

The runner is intentionally deterministic. It calls only the configured chat
HTTP boundary, records a consumer-visible projection of each answer, scores
the contract dimensions, and optionally creates deduplicated GitHub issues for
reproducible findings.
"""

from __future__ import annotations

import argparse
from copy import deepcopy
from datetime import UTC, datetime
import hashlib
import json
import os
from pathlib import Path
import re
import subprocess
import sys
import time
from typing import Any, Callable, Iterable, Mapping
from urllib.error import HTTPError, URLError
from urllib.parse import urlsplit, urlunsplit
from urllib.request import Request, build_opener


MAX_JSON_BYTES = 4_000_000
MAX_PDF_BYTES = 8_000_000
TERMINAL_STATUSES = {"available", "failed", "needs_review", "blocked"}
SENSITIVE_KEYS = {
    "authorization", "cookie", "cookies", "headers", "idempotency_key",
    "organization_id", "owner_id", "provider", "raw_html", "source_article_ids",
    "source_uri", "source_watermark", "source_watermarks", "source_revision_id",
    "source_visual_refs", "source_unnormalized", "worker_stream",
    "evidence", "evidence_id", "evidence_ids", "article_id", "provider_vehicle_id",
    "correlation_id", "request_fingerprint", "raw", "candidates", "aliases",
}
CONSUMER_COPY_BANS = (
    "source says", "source states", "source indicates", "provided pdf",
    "supplied pdf", "both sources", "article says", "generated by",
    "generation source", "provider says",
)


class ConsumerReviewError(RuntimeError):
    """A bounded transport or response-contract failure."""


def _now() -> str:
    return datetime.now(UTC).replace(microsecond=0).isoformat()


def _canonical_hash(value: Any) -> str:
    encoded = json.dumps(value, sort_keys=True, ensure_ascii=False, separators=(",", ":"), default=str).encode()
    return hashlib.sha256(encoded).hexdigest()


def _validate_base_url(value: str, *, allow_nonlocal: bool) -> str:
    parsed = urlsplit(str(value).strip())
    if parsed.scheme not in {"http", "https"} or not parsed.netloc or parsed.username or parsed.password or parsed.query or parsed.fragment:
        raise ValueError("chat API base must be an HTTP(S) origin")
    host = (parsed.hostname or "").casefold()
    local = host in {"127.0.0.1", "localhost", "::1"}
    if not local and parsed.scheme != "https":
        raise ValueError("non-local chat API must use HTTPS")
    if not local and not allow_nonlocal:
        raise ValueError("non-local chat API requires --allow-nonlocal")
    return urlunsplit((parsed.scheme, parsed.netloc, "", "", "")).rstrip("/")


class ChatHTTPClient:
    def __init__(
        self,
        base_url: str,
        *,
        timeout: float = 20,
        max_bytes: int = MAX_JSON_BYTES,
        auth_token: str = "",
        owner_id: str = "",
        organization_id: str = "",
        allow_nonlocal: bool = False,
        opener: Callable[..., Any] | None = None,
    ) -> None:
        if timeout <= 0 or max_bytes <= 0:
            raise ValueError("chat transport limits must be positive")
        self.base_url = _validate_base_url(base_url, allow_nonlocal=allow_nonlocal)
        self.timeout = timeout
        self.max_bytes = max_bytes
        self.auth_token = auth_token
        self.owner_id = owner_id
        self.organization_id = organization_id
        self.opener = opener or build_opener().open

    def _request(self, method: str, path: str, *, body: Mapping[str, Any] | None = None, idempotency_key: str = "", accept: str = "application/json") -> Any:
        if not path.startswith("/") or "?" in path or "#" in path or ".." in path.split("/"):
            raise ConsumerReviewError("chat request path is invalid")
        headers = {"Accept": accept}
        if self.auth_token:
            headers["Authorization"] = f"Bearer {self.auth_token}"
        if self.owner_id:
            headers["X-Autodata-Owner-Id"] = self.owner_id
        if self.organization_id:
            headers["X-Autodata-Organization-Id"] = self.organization_id
        payload = None
        if body is not None:
            payload = json.dumps(dict(body), ensure_ascii=False, separators=(",", ":")).encode()
            if len(payload) > self.max_bytes:
                raise ConsumerReviewError("chat request exceeds size limit")
            headers["Content-Type"] = "application/json"
        if idempotency_key:
            headers["Idempotency-Key"] = idempotency_key
        request = Request(self.base_url + path, data=payload, headers=headers, method=method)
        try:
            with self.opener(request, timeout=self.timeout) as response:
                raw = response.read(self.max_bytes + 1)
                if len(raw) > self.max_bytes:
                    raise ConsumerReviewError("chat response exceeds size limit")
                if accept == "application/pdf":
                    if not raw.startswith(b"%PDF-"):
                        raise ConsumerReviewError("chat PDF response is not a PDF")
                    return raw
                try:
                    value = json.loads(raw)
                except (UnicodeDecodeError, json.JSONDecodeError) as error:
                    raise ConsumerReviewError("chat response is not valid JSON") from error
                if not isinstance(value, Mapping):
                    raise ConsumerReviewError("chat response must be an object")
                return dict(value)
        except HTTPError as error:
            raise ConsumerReviewError(f"chat API returned HTTP {error.code}") from error
        except (URLError, TimeoutError, OSError) as error:
            raise ConsumerReviewError("chat API request failed") from error

    def create(self, message: str, idempotency_key: str) -> dict[str, Any]:
        return self._request("POST", "/chat/queries", body={"message": message}, idempotency_key=idempotency_key)

    def get(self, query_id: str) -> dict[str, Any]:
        return self._request("GET", f"/chat/queries/{_safe_id(query_id)}")

    def select(self, query_id: str, option_number: int, idempotency_key: str) -> dict[str, Any]:
        return self._request(
            "POST",
            f"/chat/queries/{_safe_id(query_id)}/selections",
            body={"selection_type": "vehicle", "option_number": option_number},
            idempotency_key=idempotency_key,
        )

    def pdf(self, query_id: str) -> bytes:
        return self._request("GET", f"/chat/queries/{_safe_id(query_id)}/guide.pdf", accept="application/pdf")


def _safe_id(value: Any) -> str:
    text = str(value or "").strip()
    if not re.fullmatch(r"[A-Za-z0-9_-]{8,128}", text):
        raise ConsumerReviewError("chat query id is invalid")
    return text


def _redact_consumer_value(value: Any, *, key: str = "") -> Any:
    if key.casefold() in SENSITIVE_KEYS:
        return None
    if isinstance(value, Mapping):
        result = {}
        for raw_key, raw_value in value.items():
            child_key = str(raw_key)
            if child_key.casefold() in SENSITIVE_KEYS:
                continue
            cleaned = _redact_consumer_value(raw_value, key=child_key)
            if cleaned is not None:
                result[child_key] = cleaned
        return result
    if isinstance(value, list):
        return [_redact_consumer_value(item) for item in value]
    return value


def _consumer_vehicle(value: Any) -> dict[str, Any]:
    if not isinstance(value, Mapping):
        return {}
    allowed = {
        "year", "make", "model", "region", "body_style", "trim", "drivetrain",
        "engine", "engine_displacement_l", "label", "vehicle_id",
    }
    return {
        key: _redact_consumer_value(value[key], key=key)
        for key in allowed
        if key in value and _redact_consumer_value(value[key], key=key) is not None
    }


def _consumer_image(value: Any) -> dict[str, Any]:
    if not isinstance(value, Mapping):
        return {}
    return {
        key: value[key]
        for key in ("url", "alt", "description", "label")
        if value.get(key) is not None
    }


def _consumer_step(value: Any) -> dict[str, Any]:
    if not isinstance(value, Mapping):
        return {}
    result = {
        key: _redact_consumer_value(value[key], key=key)
        for key in ("sequence", "phase", "components", "action", "instructions", "safety_warnings")
        if key in value and _redact_consumer_value(value[key], key=key) is not None
    }
    images = [_consumer_image(image) for image in value.get("images", []) if isinstance(image, Mapping)]
    if images:
        result["images"] = images
    return result


def _consumer_operation(value: Any) -> Any:
    if isinstance(value, str):
        return value
    if not isinstance(value, Mapping):
        return value
    return {
        key: value[key]
        for key in ("name", "title", "operation", "description", "action")
        if value.get(key) is not None
    }


def _consumer_part(value: Any) -> dict[str, Any]:
    if not isinstance(value, Mapping):
        return {}
    allowed = (
        "name", "description", "part_name", "part_number", "currency", "currency_code",
        "price", "unit_price", "total", "quantity", "priced_at", "price_date",
        "freshness", "price_freshness", "markup_applied",
    )
    return {
        key: _redact_consumer_value(value[key], key=key)
        for key in allowed
        if key in value and _redact_consumer_value(value[key], key=key) is not None
    }


def _consumer_quote(value: Any) -> dict[str, Any]:
    if not isinstance(value, Mapping):
        return {}
    allowed = (
        "total_hours", "total_labor_hours", "required_hours", "recommended_hours",
        "overlap_hours_removed", "overlap_hours", "parts",
    )
    result = {
        key: _redact_consumer_value(value[key], key=key)
        for key in allowed
        if key in value and _redact_consumer_value(value[key], key=key) is not None
    }
    for key in ("required_operations", "recommended_operations", "overlap_operations"):
        operations = value.get(key)
        if isinstance(operations, list):
            result[key] = [_consumer_operation(operation) for operation in operations]
    if isinstance(value.get("parts"), list):
        result["parts"] = [_consumer_part(part) for part in value["parts"]]
    return result


def consumer_projection(response: Mapping[str, Any]) -> dict[str, Any]:
    """Keep only the structured fields a consumer can see in the dashboard."""

    answer = response.get("answer") if isinstance(response.get("answer"), Mapping) else {}
    raw_procedure = answer.get("procedure") if isinstance(answer.get("procedure"), Mapping) else {}
    procedure_keys = ("title", "applicability", "preparation", "warnings", "gaps", "content_status", "pdf_ready", "review_state", "review_label", "revision_id")
    procedure = {
        key: _redact_consumer_value(raw_procedure[key], key=key)
        for key in procedure_keys
        if key in raw_procedure and _redact_consumer_value(raw_procedure[key], key=key) is not None
    }
    procedure["vehicle"] = _consumer_vehicle(raw_procedure.get("vehicle") or answer.get("vehicle"))
    procedure["steps"] = [_consumer_step(step) for step in raw_procedure.get("steps", []) if isinstance(step, Mapping)]
    projected_answer: dict[str, Any] = {
        key: _redact_consumer_value(answer[key], key=key)
        for key in ("answer_status", "data_state", "revision_id", "updated_at", "warnings")
        if key in answer and _redact_consumer_value(answer[key], key=key) is not None
    }
    projected_answer["vehicle"] = _consumer_vehicle(answer.get("vehicle"))
    projected_answer["procedure"] = procedure
    projected_answer["quote"] = _consumer_quote(answer.get("quote") or answer.get("labor"))
    raw_pdf = answer.get("pdf") if isinstance(answer.get("pdf"), Mapping) else {}
    projected_answer["pdf"] = {
        key: raw_pdf[key]
        for key in ("ready", "url", "revision_id")
        if key in raw_pdf and raw_pdf[key] is not None
    }
    options = response.get("vehicle_options") if isinstance(response.get("vehicle_options"), list) else []
    return {
        "query_id": response.get("query_id"),
        "status": response.get("status"),
        "vehicle_options": [_consumer_vehicle(option) | {"option_number": option["option_number"]} for option in options if isinstance(option, Mapping) and option.get("option_number") is not None],
        "answer": projected_answer,
    }


def _finding(case: Mapping[str, Any], *, finding_id: str, severity: str, category: str, path: str, message: str, reproduction: str) -> dict[str, Any]:
    return {
        "finding_id": finding_id,
        "severity": severity,
        "category": category,
        "path": path,
        "line": 0,
        "message": message,
        "reproduction": reproduction,
        "blocking": severity in {"critical", "high"},
        "resolved_by": None,
    }


def score_response(case: Mapping[str, Any], response: Mapping[str, Any], *, pdf_response: bytes | None = None) -> dict[str, Any]:
    """Score one persisted chat answer without using model-generated judgment."""

    name = str(case.get("name") or "case")
    reproduction = str(case.get("message") or name)
    answer = response.get("answer") if isinstance(response.get("answer"), Mapping) else {}
    vehicle = answer.get("vehicle") if isinstance(answer.get("vehicle"), Mapping) else {}
    procedure = answer.get("procedure") if isinstance(answer.get("procedure"), Mapping) else {}
    steps = procedure.get("steps") if isinstance(procedure.get("steps"), list) else []
    findings: list[dict[str, Any]] = []
    dimensions: dict[str, dict[str, Any]] = {}

    expected_vehicle = case.get("expected_vehicle", {})
    vehicle_ok = isinstance(expected_vehicle, Mapping) and bool(expected_vehicle)
    if vehicle_ok:
        for key, expected in expected_vehicle.items():
            if str(vehicle.get(key, "")).casefold() != str(expected).casefold():
                vehicle_ok = False
                findings.append(_finding(case, finding_id=f"{name}:vehicle:{key}", severity="high", category="quality", path=f"answer.vehicle.{key}", message=f"resolved vehicle does not match expected {key}={expected}", reproduction=reproduction))
    dimensions["applicability"] = {"passed": vehicle_ok, "evidence": {"vehicle": dict(vehicle)}}

    expected_components = [str(value) for value in case.get("expected_components", [])]
    step_components = {str(component) for step in steps if isinstance(step, Mapping) for component in (step.get("components", []) if isinstance(step.get("components"), list) else [])}
    coverage_ok = bool(procedure) and procedure.get("content_status") == "complete" and all(component in step_components or component.replace("_", " ") in str(procedure.get("title", "")).casefold() for component in expected_components)
    phases = {str(step.get("phase", "")).casefold() for step in steps if isinstance(step, Mapping)}
    if expected_components and not coverage_ok:
        findings.append(_finding(case, finding_id=f"{name}:procedure:coverage", severity="medium", category="quality", path="answer.procedure", message="procedure is not complete for every requested component", reproduction=reproduction))
    if "removal" not in phases or "installation" not in phases:
        findings.append(_finding(case, finding_id=f"{name}:procedure:phases", severity="medium", category="quality", path="answer.procedure.steps", message="procedure does not expose both removal and installation phases", reproduction=reproduction))
    min_steps = int(case.get("min_steps", 1))
    if len(steps) < min_steps:
        findings.append(_finding(case, finding_id=f"{name}:procedure:step-count", severity="medium", category="quality", path="answer.procedure.steps", message=f"procedure has {len(steps)} steps; expected at least {min_steps}", reproduction=reproduction))
    procedure_text = json.dumps(
        [
            {
                "action": step.get("action"),
                "instructions": step.get("instructions"),
                "safety_warnings": step.get("safety_warnings"),
            }
            for step in steps
            if isinstance(step, Mapping)
        ],
        ensure_ascii=False,
    ).casefold()
    required_terms = [
        str(term).strip().casefold()
        for term in case.get("required_terms", [])
        if str(term).strip()
    ]
    missing_terms = [term for term in required_terms if term not in procedure_text]
    if missing_terms:
        findings.append(_finding(case, finding_id=f"{name}:procedure:required-terms", severity="medium", category="quality", path="answer.procedure.steps", message=f"procedure is missing required depth terms: {', '.join(missing_terms)}", reproduction=reproduction))
    terms_ok = not missing_terms
    dimensions["procedure_coverage"] = {"passed": coverage_ok and "removal" in phases and "installation" in phases and len(steps) >= min_steps and terms_ok, "evidence": {"status": procedure.get("content_status"), "steps": len(steps), "phases": sorted(phases), "required_terms": required_terms, "missing_terms": missing_terms}}

    figures = [image for step in steps if isinstance(step, Mapping) for image in (step.get("images", []) if isinstance(step.get("images"), list) else []) if isinstance(image, Mapping) and image.get("url")]
    min_figures = int(case.get("min_figures", 1))
    figures_ok = len(figures) >= min_figures
    if not figures_ok:
        findings.append(_finding(case, finding_id=f"{name}:figures:minimum", severity="medium", category="quality", path="answer.procedure.steps[].images", message=f"procedure has {len(figures)} step figures; expected at least {min_figures}", reproduction=reproduction))
    dimensions["figures"] = {"passed": figures_ok, "evidence": {"figures": len(figures)}}

    review_ok = str(procedure.get("review_label") or "").casefold().startswith("unreviewed") or str(procedure.get("review_state") or "").casefold() == "unreviewed"
    warning_text = json.dumps(procedure.get("warnings", []), ensure_ascii=False).casefold()
    safety_ok = review_ok and (not case.get("require_warning") or bool(warning_text))
    if not review_ok:
        findings.append(_finding(case, finding_id=f"{name}:safety:review-label", severity="high", category="safety", path="answer.procedure.review_label", message="consumer guide is missing its UNREVIEWED label", reproduction=reproduction))
    dimensions["safety_and_review"] = {"passed": safety_ok, "evidence": {"review_label": procedure.get("review_label"), "warning_count": len(procedure.get("warnings", [])) if isinstance(procedure.get("warnings"), list) else 0}}

    public_text = json.dumps(consumer_projection(response).get("answer", {}).get("procedure", {}), ensure_ascii=False).casefold()
    banned = [phrase for phrase in CONSUMER_COPY_BANS if phrase in public_text]
    copy_ok = not banned
    if banned:
        findings.append(_finding(case, finding_id=f"{name}:copy:provenance", severity="medium", category="contract", path="answer.procedure", message=f"consumer copy contains prohibited provenance commentary: {', '.join(banned)}", reproduction=reproduction))
    dimensions["consumer_copy"] = {"passed": copy_ok, "evidence": {"banned_phrases": banned}}

    pdf_meta = answer.get("pdf") if isinstance(answer.get("pdf"), Mapping) else {}
    pdf_ready = pdf_meta.get("ready") is True
    revision_ok = bool(pdf_ready and pdf_response and pdf_response.startswith(b"%PDF-") and str(pdf_meta.get("revision_id")) == str(procedure.get("revision_id")))
    pdf_expected = procedure.get("pdf_ready") is True
    pdf_ok = revision_ok if pdf_expected else not pdf_ready
    if pdf_expected and not revision_ok:
        findings.append(_finding(case, finding_id=f"{name}:pdf:revision", severity="high", category="contract", path="answer.pdf", message="complete guide PDF is missing, invalid, or does not match the displayed revision", reproduction=reproduction))
    if not pdf_expected and pdf_ready:
        findings.append(_finding(case, finding_id=f"{name}:pdf:partial", severity="high", category="contract", path="answer.pdf.ready", message="partial guide incorrectly exposes a final PDF", reproduction=reproduction))
    dimensions["pdf_integrity"] = {"passed": pdf_ok, "evidence": {"expected": pdf_expected, "ready": pdf_ready, "revision_match": revision_ok}}

    score = round(100 * sum(1 for dimension in dimensions.values() if dimension["passed"]) / len(dimensions)) if dimensions else 0
    decision = "pass" if not findings else ("fail" if any(item["blocking"] for item in findings) else "needs_review")
    return {"case": name, "decision": decision, "score": score, "dimensions": dimensions, "findings": findings}


def _select_option(case: Mapping[str, Any], response: Mapping[str, Any]) -> int:
    options = response.get("vehicle_options") if isinstance(response.get("vehicle_options"), list) else []
    expected = case.get("expected_vehicle") if isinstance(case.get("expected_vehicle"), Mapping) else {}
    for option in options:
        if not isinstance(option, Mapping):
            continue
        if all(key in option and str(option.get(key, "")).casefold() == str(value).casefold() for key, value in expected.items()):
            return int(option.get("option_number", 0))
    if len(options) == 1 and isinstance(options[0], Mapping):
        return int(options[0].get("option_number", 0))
    raise ConsumerReviewError("case has ambiguous vehicle options without an exact match")


def run_case(
    client: ChatHTTPClient,
    case: Mapping[str, Any],
    *,
    poll_interval: float = 0.2,
    timeout: float = 60,
    idempotency_prefix: str = "consumer-review",
) -> dict[str, Any]:
    name = str(case.get("name") or "case")
    message = str(case.get("message") or "").strip()
    if not message:
        raise ConsumerReviewError(f"case {name} has no message")
    idempotency_key = f"{idempotency_prefix}:{_canonical_hash({'name': name, 'message': message})[:32]}"
    response = client.create(message, idempotency_key)
    started = time.monotonic()
    selected = False
    while True:
        status = str(response.get("status") or "").casefold()
        if status == "awaiting_vehicle":
            option_number = _select_option(case, response)
            response = client.select(str(response.get("query_id")), option_number, f"{idempotency_key}:selection")
            selected = True
            continue
        if status in TERMINAL_STATUSES:
            break
        if time.monotonic() - started >= timeout:
            raise ConsumerReviewError(f"case {name} timed out waiting for chat answer")
        time.sleep(max(0.01, poll_interval))
        response = client.get(str(response.get("query_id")))
    pdf_response = None
    answer = response.get("answer") if isinstance(response.get("answer"), Mapping) else {}
    procedure = answer.get("procedure") if isinstance(answer, Mapping) else None
    pdf_meta = answer.get("pdf") if isinstance(answer, Mapping) and isinstance(answer.get("pdf"), Mapping) else {}
    if isinstance(procedure, Mapping) and procedure.get("pdf_ready") is True and pdf_meta.get("ready") is True:
        pdf_response = client.pdf(str(response.get("query_id")))
    public_response = consumer_projection(response)
    review = score_response(case, response, pdf_response=pdf_response)
    expected_decision = str(case.get("expected_decision") or "").strip().casefold()
    if expected_decision and expected_decision not in {"pass", "fail", "needs_review", "blocked"}:
        raise ConsumerReviewError(f"case {name} has an invalid expected_decision")
    return {
        "case": name,
        "message": message,
        "selected_vehicle": selected,
        "response": public_response,
        "response_sha256": _canonical_hash(public_response),
        "pdf_sha256": hashlib.sha256(pdf_response).hexdigest() if pdf_response else None,
        "review": review,
        "expected_decision": expected_decision or None,
        "expectation_met": not expected_decision or expected_decision == review["decision"],
    }


def aggregate_decision(summary: Mapping[str, Any]) -> str:
    """Return the release decision represented by aggregate case counts."""

    if int(summary.get("fail", 0)) == 0 and int(summary.get("needs_review", 0)) == 0 and int(summary.get("blocked", 0)) == 0:
        return "pass"
    if int(summary.get("fail", 0)):
        return "fail"
    if int(summary.get("needs_review", 0)):
        return "needs_review"
    return "blocked"


def create_or_reuse_issue(
    finding: Mapping[str, Any],
    report: Mapping[str, Any],
    *,
    repository: str,
    gh_runner: Callable[[list[str]], str] | None = None,
) -> dict[str, Any]:
    """Create one issue for a stable finding, or reuse an existing issue."""

    marker = f"<!-- autodata-consumer-review:{finding['finding_id']} -->"
    runner = gh_runner or (lambda args: subprocess.run(["gh", *args], check=True, capture_output=True, text=True).stdout)
    raw = runner(["issue", "list", "--repo", repository, "--state", "all", "--limit", "1000", "--json", "number,title,body"])
    try:
        existing = json.loads(raw)
    except json.JSONDecodeError as error:
        raise ConsumerReviewError("GitHub issue listing was not valid JSON") from error
    for issue in existing if isinstance(existing, list) else []:
        if isinstance(issue, Mapping) and marker in str(issue.get("body") or ""):
            return {"finding_id": finding["finding_id"], "action": "reused", "issue_number": issue.get("number"), "marker": marker}
    title = f"Consumer review: {finding['message']}"
    body = "\n".join([
        marker,
        "## Consumer review finding",
        f"- Severity: `{finding['severity']}`",
        f"- Category: `{finding['category']}`",
        f"- Case: `{report.get('case')}`",
        f"- Implementation SHA: `{report.get('implementation_sha')}`",
        f"- Report: `{report.get('report_path')}`",
        f"- Response SHA256: `{report.get('response_sha256')}`",
        "",
        finding["message"],
        "",
        f"Reproduction: `{finding['reproduction']}`",
    ])
    safe_finding_id = re.sub(r"[^A-Za-z0-9._-]+", "-", str(finding["finding_id"])).strip("-")
    body_path = Path(str(report["report_path"])).with_suffix(f".{safe_finding_id}.issue.md")
    label = {"quality": "type:data-quality", "safety": "type:security", "reliability": "type:infrastructure"}.get(str(finding.get("category")), "type:bug")
    body_path.write_text(body, encoding="utf-8")
    created = runner(["issue", "create", "--repo", repository, "--title", title, "--body-file", str(body_path), "--label", label])
    issue_number = re.search(r"/issues/(\d+)", created).group(1) if re.search(r"/issues/(\d+)", created) else None
    return {"finding_id": finding["finding_id"], "action": "created", "issue_number": issue_number, "marker": marker}


def _load_cases(path: Path) -> list[dict[str, Any]]:
    value = json.loads(path.read_text(encoding="utf-8"))
    if isinstance(value, Mapping):
        value = value.get("cases")
    if not isinstance(value, list) or not all(isinstance(item, Mapping) for item in value):
        raise ValueError("case file must contain a list or an object with a cases list")
    return [dict(item) for item in value]


def run_cases(
    cases: Iterable[Mapping[str, Any]],
    *,
    client: ChatHTTPClient,
    implementation_sha: str,
    report_dir: Path,
    repository: str = "",
    create_issues: bool = False,
) -> dict[str, Any]:
    run_id = hashlib.sha256(f"{implementation_sha}:{_now()}".encode()).hexdigest()[:24]
    report_dir.mkdir(parents=True, exist_ok=True)
    results: list[dict[str, Any]] = []
    for case in cases:
        try:
            results.append(run_case(client, case, idempotency_prefix=f"consumer-review:{run_id}"))
        except ConsumerReviewError as error:
            results.append({"case": case.get("name", "case"), "message": case.get("message", ""), "response": None, "response_sha256": None, "pdf_sha256": None, "review": {"case": case.get("name", "case"), "decision": "blocked", "score": 0, "dimensions": {}, "findings": [{"finding_id": f"{case.get('name', 'case')}:transport", "severity": "high", "category": "reliability", "path": "transport", "line": 0, "message": str(error), "reproduction": str(case.get("message", "")), "blocking": True, "resolved_by": None}]}})
    decisions = [str(result["review"].get("decision")) for result in results]
    decision = aggregate_decision({
        "pass": decisions.count("pass"),
        "fail": decisions.count("fail"),
        "needs_review": decisions.count("needs_review"),
        "blocked": decisions.count("blocked"),
    })
    aggregate: dict[str, Any] = {
        "run_id": run_id,
        "agent": "autodata-consumer-agent",
        "implementation_sha": implementation_sha,
        "created_at": _now(),
        "report_path": str(report_dir / f"consumer-review-{run_id}.json"),
        "cases": results,
        "summary": {"case_count": len(results), "pass": decisions.count("pass"), "fail": decisions.count("fail"), "needs_review": decisions.count("needs_review"), "blocked": decisions.count("blocked")},
        "decision": decision,
        "issue_actions": [],
    }
    Path(aggregate["report_path"]).write_text(json.dumps(aggregate, indent=2, ensure_ascii=False, sort_keys=True) + "\n", encoding="utf-8")
    if create_issues:
        if not repository:
            raise ValueError("--create-issues requires --repository")
        for result in results:
            review = result.get("review", {})
            for finding in review.get("findings", []) if isinstance(review, Mapping) else []:
                if isinstance(finding, Mapping) and finding.get("severity") != "info":
                    issue_report = {"case": result.get("case"), "implementation_sha": implementation_sha, "report_path": aggregate["report_path"], "response_sha256": result.get("response_sha256")}
                    aggregate["issue_actions"].append(create_or_reuse_issue(finding, issue_report, repository=repository))
        Path(aggregate["report_path"]).write_text(json.dumps(aggregate, indent=2, ensure_ascii=False, sort_keys=True) + "\n", encoding="utf-8")
    return aggregate


def _git_sha() -> str:
    return subprocess.run(["git", "rev-parse", "HEAD"], check=True, capture_output=True, text=True).stdout.strip()


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--api-base-url", default=os.getenv("AUTODATA_CHAT_BASE_URL", "http://127.0.0.1:8080"))
    parser.add_argument("--case-file", type=Path, action="append", required=True)
    parser.add_argument("--report-dir", type=Path, required=True)
    parser.add_argument("--implementation-sha", default="")
    parser.add_argument("--repository", default=os.getenv("GITHUB_REPOSITORY", ""))
    parser.add_argument("--timeout", type=float, default=60)
    parser.add_argument("--allow-nonlocal", action="store_true")
    parser.add_argument("--create-issues", action="store_true")
    args = parser.parse_args(argv)
    try:
        cases = [case for path in args.case_file for case in _load_cases(path)]
        client = ChatHTTPClient(args.api_base_url, timeout=args.timeout, auth_token=os.getenv("AUTODATA_CHAT_AUTH_TOKEN", ""), owner_id=os.getenv("AUTODATA_CHAT_OWNER_ID", ""), organization_id=os.getenv("AUTODATA_CHAT_ORGANIZATION_ID", ""), allow_nonlocal=args.allow_nonlocal)
        report = run_cases(cases, client=client, implementation_sha=args.implementation_sha or _git_sha(), report_dir=args.report_dir, repository=args.repository, create_issues=args.create_issues)
    except (OSError, ValueError, ConsumerReviewError) as error:
        print(json.dumps({"agent": "autodata-consumer-agent", "decision": "blocked", "error": str(error)}, sort_keys=True))
        return 2
    decisions = report["summary"]
    decision = aggregate_decision(decisions)
    print(json.dumps({"agent": report["agent"], "run_id": report["run_id"], "decision": decision, "summary": decisions, "report_path": report["report_path"], "issue_actions": report["issue_actions"]}, sort_keys=True))
    return 0 if decision == "pass" else 1


if __name__ == "__main__":
    sys.exit(main())
